cc_library(
    name = 'chive_http',
    srcs = [
        'HttpRequest.cc',
        'HttpResponse.cc',
        'HttpContext.cc',
        'HttpServer.cc',
    ],
    extra_cppflags = [
        '-std=c++17',
        # '-Wall',  # show warning as error
        '-w',       # no warning
         '-g',
    ]
)
