cc_library(
    name = 'chive_net',
    srcs = [
        'EventLoop.cc',
        'Channel.cc',
        'Poller.cc',
        'poller/EPollPoller.cc',
        'TimerQueue.cc',
        'Timer.cc'
    ],
    deps = [
   #     '//chive/net/poller/:chive_net_poller'
    ]
)
