cc_library(
    name = 'chive_net',
    srcs = [
        'EventLoop.cc',
        'Channel.cc',
        'Poller.cc',
        'poller/EPollPoller.cc',
        'TimerQueue.cc',
        'Timer.cc',
        'Acceptor.cc',
        'Socket.cc',
        'InetAddress.cc',
        'TcpConnection.cc',
        'TcpServer.cc',
    ],
    deps = [
   #     '//chive/net/poller/:chive_net_poller'
    ]
)
