cc_binary(
    name = 'reactor',
    srcs = [
        'test.cc'
    ],
    deps = [
        '//chive/net/:chive_net',
        '//chive/base/:chive_base',
        '#pthread'
    ],
    extra_cppflags = [
        '-std=c++14',
#        '-Wall',
    ]
)