cc_library(
    name = 'chive_base',
    srcs = [
        'Logger.cc',
        #'Condition.h',
        'CurrentThread.cc',
        'CountDownLatch.cc',
        #'MutexLock.h'
    ],
    deps = [
        '#pthread'
    ]
)