cc_library(
    name = 'chive_base',
    srcs = [
        'Logger.cc',
        'CurrentThread.cc',
        'CountDownLatch.cc',
    ],
    deps = [
        '#pthread',
        '//chive/base/clog/:chive_log'
    ]
)