cc_library(
    name = 'chive_log',
    srcs = [
        'chiveLog.cc'
    ],
    extra_cppflags = [
        '-std=c++17',
        # '-Wall',  # show warning as error
        '-w',       # no warning
         '-g',
    ]
)